name: Release
on:
  create:
    tags:
      - v*

jobs:
  release:
    name: Release on GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Validates GO releaser config
        uses: docker://goreleaser/goreleaser:latest
        with:
          args: check

      - name: Create client on GitHub
        uses: docker://goreleaser/goreleaser:latest
        with:
          args: release
          workdir: go-proxy/client/
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Create server on GitHub
        uses: docker://goreleaser/goreleaser:latest
        with:
          args: release
          workdir: go-proxy/server/
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}